### ISSUE TITLE
Differentiation beween django-money and django-moneyfield

### ISSUE THREAD

**Issue by codingjoe** [carlospalol/django-moneyfield#1]
I was wondering, what the difference between these tow libs is. I just did a major rewrite of django-money, and now they are really similar. I figured, that they are almost the same now.

How about combining efforts? Rather than having 2 identical libs we should really have one good one.

BTW:
Did you write it from scratch?

**Comment by carlospalol** [comment]
Hello Johannes, it is an original package and has some differences both in the code and in the usage. I have just added a new section in the README explaining a bit better the difference.

**Comment by codingjoe** [comment]
Sweet, I'm gonna read it tomorrow. Maybe I can be of some help as such a field seems to be of importance for everyone who needs to make actual money on the web.
